### ISSUE TITLE
field for "No. Telepon" -> text

### ISSUE THREAD

**Issue by luridarmawan** [devcjakarta/facebook-hackathon#10]
better using text for "No. Telepon" field, rather than number

**Comment by kevin-hyperjump** [comment]
Fixed with (https://github.com/devcjakarta/facebook-hackathon/commit/40d4d191a412f2ec32a01057e28acda48e74ca30)

**Comment by achmadk** [comment]
harusnya udah bener di set ke number @kevinhermawan . Nanti kalo di smartphone input keyboard-nya cuma berupa angka. Terus `this.state.phoneNumber` udah otomatis nyimpen noHP ke string.

kalo di-set ke text, input keyboard-nya qwerty gitu kalo web-nya dibuka lewat smartphone.

**Comment by kevin-hyperjump** [comment]
Nanti mas @achmadk dirundingkan lagi :+1:
