### ISSUE TITLE
Register with Facebook

### ISSUE THREAD

**Issue by kevin-hyperjump** [devcjakarta/facebook-hackathon#5]

**Comment by achmadk** [comment]
udah aku tambahin `react-social-login` Vin.

**UPDATE 18 September 2017**
sudah menggunakan `react-sosial-plugin`. Mengalami error karena development mode-nya belum dimatikan sama @imamaris 

**UPDATE 20 September 2017**
Development mode-nya sudah dimatikan, tetapi belum menambahkan `localhost` dan `jakarta.devcid.com/hackathon` ke daftar alamat domain.  

Setelah menambahkan alamat domain dan callback URI, tetap saja mengalami error. Ternyata perlu diaktifkan opsi Masuk OAuth Klien sama Masuk OAuth Web sehingga berhasil login menggunakan facebook.

Sementara mengambil nama lengkap dan email ke formulir pendaftaran

**Comment by luridarmawan** [comment]
waktu "Register with Facebook", ada gini di log:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
`
