### ISSUE TITLE
Add regular expression

### ISSUE THREAD

**Issue by kevin-hyperjump** [devcjakarta/facebook-hackathon#6]
## Regex for :
1. Phone number
2. E-mail

**Comment by achmadk** [comment]
Pake validator.js Vin. kalo email bisa `isEmail(email)`.

Kalo noHP `isMobilePhone(phoneNumber, 'id-ID')` ditambah rentang digit ya diantara 8-13.

Semoga bisa membantu

**Comment by kevin-hyperjump** [comment]
Sebenernya sih lebih mudah pake Regex mas, cuma belum sempet ngerjain :laughing: 

Makanya dibuat issue biar yang lain bisa bantu juga :smiley:

**Comment by achmadk** [comment]
fungsi2 yang ada di `validator` juga pake regex kok Vin.

**Comment by kevin-hyperjump** [comment]
Saya belum nyoba si mas @achmadk, mungkin nanti saya coba, nice info :+1:
